---
title: "Geo Location of the landrace samples"
output: html_notebook
author: Jinliang Yang
---


```{r setup, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE) 
knitr::opts_knit$set(root.dir=normalizePath('../../')) 
#library(tidyverse)
```

### V2 => V4

```{r}
v2 <- read.csv("data/ISU_integrated_IBM_AGPv2_training.csv")

v2$Physical <- as.numeric(as.character(gsub(",", "", v2$Physical)))
v2 <- v2[, c("Chr", "Physical", "Physical", "Marker")]
v2$Physical <- v2$Physical -1
write.table(v2, "data/ISU_v2.bed", sep="\t", row.names=FALSE, quote=FALSE)
```

```{r}
v4 <- read.csv("data/ISU_v2_v4.bed", sep="\t", header=FALSE)

v2 <- read.csv("data/ISU_integrated_IBM_AGPv2_training.csv")

map <- merge(v2, v4, by.x="Marker", by.y="V4")
sum(map$Chr != map$V1) #32
map <- subset(map, Chr == V1)
map <- map[, c(1:4, 7)]
names(map)[4:5] <- c("v2", "v4")
write.table(map, "data/ISU_integrated_IBM_v2_v4.txt", sep="\t", row.names=FALSE, quote=FALSE)
```

# purpose: using p2g to find the genetic map of a give physical pos

```{r}


use_p2g <- function(BINSIZE=100000){
  source("lib/p2g.R")
  train <- read.table("data/ISU_integrated_IBM_v2_v4.txt", header=TRUE)
  #train$Physical <- as.numeric(as.character(gsub(",", "", train$Physical)))
  ### test the proformance of the function using the training data
  names(train)[5] <- "Physical"
  
  ### read run
  cl <- read.csv("data/chr_length_B73v4.csv")
  df <- data.frame()
  for(i in 1:10){
    tem <- data.frame(marker=1, chr=i, Physical=1:round(cl[cl$Chr ==i,]$BP/BINSIZE,0))
    tem$Physical <- tem$Physical*BINSIZE
    tem$marker <- paste(tem$chr, round(tem$Physical/BINSIZE,0), sep="_")
    out2 <- p2g(tem, train)
    df <- rbind(df, out2)
  }
  
  return(df)
}

df <- use_p2g(BINSIZE=100000)
write.table(df, "data/v4_physical_genetic.csv", sep=",", row.names=FALSE)
```







