---
title: "Plot genomic feature MCMC BC"
output: html_notebook
author: Jinliang Yang
date: 02-08-2019
---


```{r setup, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE) 
knitr::opts_knit$set(root.dir=normalizePath('../../')) 
#library(tidyverse)
```


### Teosinte Genome-wide results

CG

```{r}
### Jinliang Yang
### 10-14-2016
### run MCMC for comet on chr10

source("lib/mplots.R")
source("lib/mcmcbc.R")

ob <- load("largedata/msfs/gf2_sfs_interpop_CG_down.RData")
sfsplot(res,burnin=0.2,rates=c(1E8,1E8,1E8), sfsplot="plotmean", Ne=150000, k=0:102)
out1 <- mplot(res, burnin=0.2, rates=c(1E8,1E8,1E5))
#

ob <- load("largedata/msfs/gf2_sfs_interpop_CG_up.RData")
sfsplot(res,burnin=0.2,rates=c(1E8,1E8,1E8), sfsplot="plotmean", Ne=150000, k=0:102)
out2 <- mplot(res, burnin=0.2, rates=c(1E8,1E8,1E5))
# posterior mu [ 4.60934455109854e-07 ], nu [ 6.77645732778247e-07 ] and s [ 1.79033264284426e-06 ]


ob <- load("largedata/msfs/gf2_sfs_interpop_CG_gene.RData")
sfsplot(res,burnin=0.2,rates=c(1E8,1E8,1E8), sfsplot="plotmean", Ne=150000, k=0:102)
out3 <- mplot(res, burnin=0.2, rates=c(1E8,1E8,1E5))
#
```

CHG

```{r}
### Jinliang Yang
### 10-14-2016
### run MCMC for comet on chr10

source("lib/mplots.R")
source("lib/mcmcbc.R")

ob <- load("largedata/msfs/gf2_sfs_interpop_CHG_down.RData")
sfsplot(res,burnin=0.2,rates=c(1E8,1E8,1E8), sfsplot="plotmean", Ne=150000, k=0:102)
out1 <- mplot(res, burnin=0.2, rates=c(1E8,1E8,1E5))
#

ob <- load("largedata/msfs/gf2_sfs_interpop_CHG_up.RData")
sfsplot(res,burnin=0.2,rates=c(1E8,1E8,1E8), sfsplot="plotmean", Ne=150000, k=0:102)
out2 <- mplot(res, burnin=0.2, rates=c(1E8,1E8,1E5))
# posterior mu [ 4.60934455109854e-07 ], nu [ 6.77645732778247e-07 ] and s [ 1.79033264284426e-06 ]


ob <- load("largedata/msfs/gf2_sfs_interpop_CHG_gene.RData")
sfsplot(res,burnin=0.2,rates=c(1E8,1E8,1E8), sfsplot="plotmean", Ne=150000, k=0:102)
out3 <- mplot(res, burnin=0.2, rates=c(1E8,1E8,1E5))
#
```


-----------------------------------------

### Hypo and Hyper features

CG

```{r}
### Jinliang Yang
### 10-14-2016
### run MCMC for comet on chr10

source("lib/mplots.R")
source("lib/mcmcbc.R")

ob <- load("largedata/msfs/gf3_sfs_interpop_CG_hypo_down.RData")
#sfsplot(res,burnin=0.2,rates=c(1E8,1E8,1E8), sfsplot="plotmean", Ne=150000, k=0:102)
out1 <- mplot(res, burnin=0.2, rates=c(1E8,1E8,1E5))
#

ob <- load("largedata/msfs/gf3_sfs_interpop_CG_hypo_up.RData")
#sfsplot(res,burnin=0.2,rates=c(1E8,1E8,1E8), sfsplot="plotmean", Ne=150000, k=0:102)
out2 <- mplot(res, burnin=0.2, rates=c(1E8,1E8,1E5))
# posterior mu [ 4.60934455109854e-07 ], nu [ 6.77645732778247e-07 ] and s [ 1.79033264284426e-06 ]


ob <- load("largedata/msfs/gf3_sfs_interpop_CG_hypo_gene.RData")
#sfsplot(res,burnin=0.2,rates=c(1E8,1E8,1E8), sfsplot="plotmean", Ne=150000, k=0:102)
out3 <- mplot(res, burnin=0.2, rates=c(1E8,1E8,1E5))

ob <- load("largedata/msfs/gf3_sfs_interpop_CG_hyper_down.RData")
#sfsplot(res,burnin=0.2,rates=c(1E8,1E8,1E8), sfsplot="plotmean", Ne=150000, k=0:102)
out4 <- mplot(res, burnin=0.2, rates=c(1E8,1E8,1E5))
#

ob <- load("largedata/msfs/gf3_sfs_interpop_CG_hyper_up.RData")
#sfsplot(res,burnin=0.2,rates=c(1E8,1E8,1E8), sfsplot="plotmean", Ne=150000, k=0:102)
out5 <- mplot(res, burnin=0.2, rates=c(1E8,1E8,1E5))
# posterior mu [ 4.60934455109854e-07 ], nu [ 6.77645732778247e-07 ] and s [ 1.79033264284426e-06 ]

ob <- load("largedata/msfs/gf3_sfs_interpop_CG_hyper_gene.RData")
#sfsplot(res,burnin=0.2,rates=c(1E8,1E8,1E8), sfsplot="plotmean", Ne=150000, k=0:102)
out6 <- mplot(res, burnin=0.2, rates=c(1E8,1E8,1E5))

df1 <- rbind(out1, out2, out3, out4, out5, out6)
df1 <- as.data.frame(df1)
names(df1) <- c("mu", "nu", "s")
df1$Nes <- 150000*df1$s
df1$gf <- c("CG_hypo_up", "CG_hypo_down","CG_hypo_gene", "CG_hyper_up", "CG_hyper_down","CG_hyper_gene")
```

CHG

```{r}
### Jinliang Yang
### 10-14-2016
### run MCMC for comet on chr10

source("lib/mplots.R")
source("lib/mcmcbc.R")

ob <- load("largedata/msfs/gf3_sfs_interpop_CHG_hypo_down.RData")
#sfsplot(res,burnin=0.2,rates=c(1E8,1E8,1E8), sfsplot="plotmean", Ne=150000, k=0:102)
out1 <- mplot(res, burnin=0.2, rates=c(1E8,1E8,1E5))
#

ob <- load("largedata/msfs/gf3_sfs_interpop_CHG_hypo_up.RData")
#sfsplot(res,burnin=0.2,rates=c(1E8,1E8,1E8), sfsplot="plotmean", Ne=150000, k=0:102)
out2 <- mplot(res, burnin=0.2, rates=c(1E8,1E8,1E5))
# posterior mu [ 4.60934455109854e-07 ], nu [ 6.77645732778247e-07 ] and s [ 1.79033264284426e-06 ]


ob <- load("largedata/msfs/gf3_sfs_interpop_CHG_hypo_gene.RData")
#sfsplot(res,burnin=0.2,rates=c(1E8,1E8,1E8), sfsplot="plotmean", Ne=150000, k=0:102)
out3 <- mplot(res, burnin=0.2, rates=c(1E8,1E8,1E5))

ob <- load("largedata/msfs/gf3_sfs_interpop_CHG_hyper_down.RData")
#sfsplot(res,burnin=0.2,rates=c(1E8,1E8,1E8), sfsplot="plotmean", Ne=150000, k=0:102)
out4 <- mplot(res, burnin=0.2, rates=c(1E8,1E8,1E5))
#

ob <- load("largedata/msfs/gf3_sfs_interpop_CHG_hyper_up.RData")
#sfsplot(res,burnin=0.2,rates=c(1E8,1E8,1E8), sfsplot="plotmean", Ne=150000, k=0:102)
out5 <- mplot(res, burnin=0.2, rates=c(1E8,1E8,1E5))
# posterior mu [ 4.60934455109854e-07 ], nu [ 6.77645732778247e-07 ] and s [ 1.79033264284426e-06 ]

ob <- load("largedata/msfs/gf3_sfs_interpop_CHG_hyper_gene.RData")
#sfsplot(res,burnin=0.2,rates=c(1E8,1E8,1E8), sfsplot="plotmean", Ne=150000, k=0:102)
out6 <- mplot(res, burnin=0.2, rates=c(1E8,1E8,1E5))

df2 <- rbind(out1, out2, out3, out4, out5, out6)
df2 <- as.data.frame(df2)
names(df2) <- c("mu", "nu", "s")
df2$Nes <- 150000*df2$s
df2$gf <- c("CHG_hypo_up", "CHG_hypo_down","CHG_hypo_gene", "CHG_hyper_up", "CHG_hyper_down","CHG_hyper_gene")
```



```{r}
df <- rbind(df1, df2)
df$context <- gsub("_.*", "", df$gf)
df$type <- gsub(".*G_", "", df$gf)
df$feature <- gsub(".*_", "", df$type)
df$type <- gsub("_.*", "", df$type)
write.table(df, "cache/gf3_par_msfs.csv", sep=",", row.names=FALSE, quote=FALSE)

```

