---
title: "Genomic feature selection using AGPV4 Annotation"
output: html_notebook
author: Jinliang Yang
date: 02-07-2019
---


```{r setup, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE) 
knitr::opts_knit$set(root.dir=normalizePath('../../')) 
#library(tidyverse)
```



Note, require `R/3.5` or above for the following step:

```{r, eval=FALSE}

get_DMR_sfs <- function(pop1="largedata/mr_100bp/teosinte_CpG_matrix_imp.csv", 
                   pop2="largedata/mr_100bp/landrace_CpG_matrix_imp.csv",
                   pop3="largedata/mr_100bp/maize_CpG_matrix_imp.csv",
                   dmrfile="data/all_DMRs.txt", context="CG", outpath="cache/DMR_jSFS_"){
    
    df1 <- fread(pop1, data.table=FALSE)
    df2 <- fread(pop2, data.table=FALSE)
    df3 <- fread(pop3, data.table=FALSE)
    
    df <- merge(df1, df2[, -2:-3], by="uid")
    df <- merge(df, df3[, -2:-3], by="uid")
    
    ###########
    chr <- df[, 1:3]
    chr$start <- as.numeric(as.character(df$pos)) - 100+1
    chr$end <- as.numeric(as.character(df$pos))
    gr1 = with(chr, GRanges(seqnames=chr, IRanges(start=start, end=end), strand="+", uid=uid))
    
    
    f <- read.delim(dmrfile)
    f <- subset(f, Type %in% context)
    gr0 = with(f, GRanges(seqnames=chr, IRanges(start=start, end=stop), strand="+" ))
    feature <- gr0
    ex1 = findOverlaps(feature, gr1)
    out <- gr1[subjectHits(ex1)]
    
    mydf <- subset(df, uid %in% mcols(out)$uid)
    message(sprintf("###>>> [%s] rows and [%s] cols for context [%s], sfs...", nrow(mydf), ncol(mydf), context))
    #########
      #df <- as.data.frame(df)
    #ftb <- apply(mydf[, -1:-3], 1, getcount)
    #sfs <- table(ftb)
    outfile <- paste0(outpath, context, ".csv")
    write.table(mydf, outfile, sep=",", row.names=FALSE, quote=FALSE)
    
}

library("plyr")
compute_jsfs <- function(mydf="cache/DMR_jSFS_CG.csv", p1cols=4:23, p2cols=24:40, p3cols=41:54){
  d <- read.csv(mydf)
  ftb1 <- apply(d[, p1cols], 1, getcount)
  sfs1 <- as.data.frame(table(ftb1))
  sfs1$bin <- cut(as.numeric(as.character(sfs1[,1])), 10)
  out1 <- ddply(sfs1, .(bin), summarise,
                Freq = sum(Freq))
  out1$bin <- 1:nrow(out1)
  out1$pop <- "teosinte"
  #g1 <- as.data.frame(table(cut(as.numeric(as.character(sfs1[,1])), 10)))
  
  ftb2 <- apply(d[, p2cols], 1, getcount)
  sfs2 <- as.data.frame(table(ftb2))
  sfs2$bin <- cut(as.numeric(as.character(sfs2[,1])), 10)
  out2 <- ddply(sfs2, .(bin), summarise,
                Freq = sum(Freq))
  out2$bin <- 1:nrow(out2)
  out2$pop <- "landrace"
  
  ftb3 <- apply(d[, p3cols], 1, getcount)
  sfs3 <- as.data.frame(table(ftb3))
  sfs3$bin <- cut(as.numeric(as.character(sfs3[,1])), 10)
  out3 <- ddply(sfs3, .(bin), summarise,
                Freq = sum(Freq))
   out3$bin <- 1:nrow(out3)
  out3$pop <- "maize"
  
  out <- rbind(out1, out2, out3)
  #out$bin <- paste0("bin", out$bin)
  return(out)
  
}

getcount <- function(x, mmin=0.3, mmax=0.7){
    n0 <- sum(x < mmin) #0
    n2 <- sum(x > mmax) #2
    n1 <- sum(x >= mmin & x <= mmax) #1
    return(2*n2+n1)
}


library("GenomicRanges")
library("data.table")

ob <- load("largedata/AGPv4_genomic_features.RData")

# CG
get_DMR_sfs(pop1="largedata/mr_100bp/teosinte_CpG_matrix_imp.csv", 
            pop2="largedata/mr_100bp/landrace_CpG_matrix_imp.csv",
            pop3="largedata/mr_100bp/elite_rm_CpG_matrix_imp.csv",
            dmrfile="data/all_DMRs.txt", context="CG", outpath="cache/DMR_sfs_interpop_")





  
# CHG  
get_DMR_sfs(pop1="largedata/mr_100bp/teosinte_CHG_matrix_imp.csv", 
            pop2="largedata/mr_100bp/landrace_CHG_matrix_imp.csv",
            pop3="largedata/mr_100bp/elite_rm_CHG_matrix_imp.csv",
            dmrfile="data/all_DMRs.txt", context="CHG", outpath="cache/DMR_sfs_interpop_")
  
# CHH 
get_DMR_sfs(pop1="largedata/mr_100bp/teosinte_CHH_matrix_imp.csv", 
            pop2="largedata/mr_100bp/landrace_CHH_matrix_imp.csv",
            pop3="largedata/mr_100bp/elite_rm_CHH_matrix_imp.csv",
            dmrfile="data/all_DMRs.txt", context="CHH", outpath="cache/DMR_sfs_interpop_")

```


### Plot the results


### CHH need to be modified:
```{r, eval=FALSE}
library(ggplot2)

out0 <- subset(out, pop %in% c("teosinte", "maize"))
fsize=18
p <- ggplot(out0, aes(x=as.factor(bin), y=Freq, fill=pop)) +
    #facet_grid(. ~ type) +
    geom_bar(stat="identity", position=position_dodge()) +
    theme_bw() +
    xlab("") +
    ylab("") +
    # https://www.color-hex.com/color-palette/73961
    #scale_fill_manual(values=c("#cc4141", "#72114b", "#e1cd07", "#5f9057", "#114c63", "#d3d3d3"),
    #                  name=c(""),
    #                  labels=c("Gene", "Down 5k", "Up 5k", "Intergenic", "TE", "Rest")) +
    scale_fill_manual(values=c("#ae5a41", "#1b85b8")) +
    #                   name="", labels=c("TEO", "LR", "MZ")) +
    #scale_x_discrete(labels=c("Hyper","Hypo")) +
    #theme(legend.position="top", axis.text=element_text(size=12), axis.title=element_text(size=15) )
    theme(#axis.text.x=element_blank(), #axis.ticks.x=element_blank(),
          axis.text=element_text(size=fsize),
          axis.title=element_text(size=fsize, face="bold"),
          legend.title = element_text(size=fsize, face="bold"),
          legend.text = element_text(size=fsize)) +
      xlab("Sites (bin)") + 
      ylab("Freq (100-bp tile)")
  #########

pdf("graphs/jmSFS_teo_mz_DMRs.pdf", width=8, height=5)
p
dev.off()
```


