---
title: "Plot genomic feature MCMC BC"
output: NULL
author: Jinliang Yang
date: 02-08-2019
---


```{r setup, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE) 
knitr::opts_knit$set(root.dir=normalizePath('../../')) 
#library(tidyverse)
```


### Teosinte Genome-wide results

CG

```{r}
equ_methylome <- function(mu = 1.3*10^-6, nu = 5.6*10^-8, ngen=10^5,
                          genomesize=10^6, msites=8*10^5){
  df <- data.frame(ngen=0, size=genomesize, msites=msites, umsites=2*10^5)
  out <- df
  for(i in 1:ngen){
  # the current generation:
    print(i)
    out$ngen <- i
    out$msites <- out$msites + mu*out$umsites # from unmethy => meth
    out$msites <- out$msites - nu*out$msites
    out$umsites <- out$size - out$msites
    df <- rbind(df, out)
  }
  df$rate <- df$msites/df$size
  return(df)
}

  
#unmethylated 
df1 <- equ_methylome(mu = 1.3*10^-6, nu = 5.6*10^-8, ngen=10^6,
                     genomesize=10^7, msites=9*10^6)
  
plot(df1$ngen, df1$msites)


  
mu1 = 2.56*10^-4
nu = 6.3*10^-4

#unmethylated 
df1 <- equ_methylome(mu = 1.3*10^-3, nu = 5.6*10^-5, ngen=10^4,
                     genomesize=10^7, msites=8*10^6)
  
plot(df1$ngen, df1$msites)

#unmethylated 
df2 <- equ_methylome(mu = 2.9*10^-3, nu = 1*10^-4, ngen=10^4,
                     genomesize=10^7, msites=8*10^6)
  
plot(df2$ngen, df2$msites)

#unmethylated 
df3 <- equ_methylome(mu = 1.3*10^-5, nu = 4.4*10^-3,  ngen=10^4,
                     genomesize=10^7, msites=0)
  
plot(df3$ngen, df3$msites)



library("data.table")
tb <- fread("/common/jyanglab/shared/Gen_Xu/07-08-2019-mr_100bptile/Teosinte/CHH/CHH_JRIAL2T.100bp_meth.txt", data.table=FALSE)

sum(tb$Meth > 0.2)/nrow(tb)

df$rate <- df$msites/df$size
plot(df$ngen, df$rate)

```


