---
title: "Plot results"
output: html_notebook
---


```{r setup, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE) 
knitr::opts_knit$set(root.dir=normalizePath('../../')) 
#library(tidyverse)
```


```{r}
library("beanplot")
library("dplyr")
library(tidyr)


plot_beans <- function(asb, bg, mytrait="asiavg"){
  
  bg1 <- subset(bg, trait %in% mytrait)
  bg1 <- gather(data=bg1, key=k, value="var", 1:6)
  
  #### for trait perse
  bg1$key <- gsub(".*_K", "K", bg1$k)
  #bg1$key <- as.numeric(as.character(bg1$key))
  bg1$var <- as.numeric(as.character(bg1$var))
  
  asb1 <- subset(asb, trait %in% mytrait)
  asb1 <- gather(data=asb1, key=key, value="val", 2:7)
  
  beanplot(var ~ as.factor(key), data = bg1, ll = 0.04, cex=1.5, border = NA,
         what=c(0, 1, 0, 1), col=c(c("antiquewhite3", "black")), cex=1, 
         xlab="", ylab="Variance Explained", main= asb1$pretty_name[1])
  for(i in 1:nrow(asb1)){
    lines(x=c(i-0.3, i+0.3), y=c(asb1$val[i], asb1$val[i]), lwd=2, col="red")
  }
}

########
asb <- read.csv("cache/h2_asb_K1-5.csv")
asb <- subset(asb, Her_ALL > 0.4)

bg <- read.csv("cache/h2_bg_updated.csv")
bg$rep <- gsub("_NAM_.*", "", bg$trait)
bg$trait <- gsub(".*NAM_", "", bg$trait)


pdf("graphs/var_explained.pdf", width=8, height=8)
for(i in c(1:14, 16:nrow(asb))){
  plot_beans(asb, bg, mytrait=asb$trait[i])
}
dev.off()
```

K1: asb_gene.bed.kinship
K2: asb_nonGenic.bed.kinship
K3: asb_post_gene_1kb.bed.kinship
K4: asb_promoter_1kb.bed.kinship
K5: asb_promoter_5kb.bed.kinship
K6: asb_res_kinship

