---
title: "plot results"
output: NULL
date: 07-16-2020
---


```{r setup, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE) 
knitr::opts_knit$set(root.dir=normalizePath('../../')) 
#library(tidyverse)
```


### Bar plot

CHG teosinte and landrace
```{r}

library("dplyr")
library("tidyr")
library("ggplot2")

mybarplot <- function(df=cg){
  
 
  sub <- df[, c("pretty_name", "Her_K1", "Her_K2", "Her_K3", "Her_K4", "Her_K5")]
  sub$h2 <- sub$Her_K1 + sub$Her_K2 + sub$Her_K3 + sub$Her_K4 + sub$Her_K5
  sub <- sub[order(sub$h2, decreasing = FALSE),]

  df0 <- gather(data=sub, key=k, value="var", 2:6)
  df0$pretty_name <- factor(df0$pretty_name, levels = sub$pretty_name)
  df0$k <- factor(df0$k, levels = c( "Her_K1", "Her_K2", "Her_K3", "Her_K4", "Her_K5"),
                    labels =c("Completely unmethylated", "completely methylated", "rarely unmethylated","rarely methylated", "commonly methylated"))


  
  p <- ggplot(df0, aes(x=pretty_name, y=var, fill=k), position = position_stack(reverse = TRUE)) +
    geom_bar(stat="identity") +
    coord_flip() +
    theme_bw() +
    xlab("") +
    ylab("") +
    geom_hline(yintercept=0.1, linetype="dotted") +
    scale_x_discrete(position = "top") +
    geom_vline(xintercept=0.1, linetype="dotted") +
    # https://www.color-hex.com/color-palette/73961
    scale_fill_manual(values=c("#cc4141", "#72114b", "#e1cd07", "red", "blue")) +
    #scale_fill_discrete(name="", labels=c("Exon", "Intron")) +
    theme(legend.position=c(0.8, 0.1), axis.text=element_text(size=12), axis.title=element_text(size=15) )
  #########
  return(p)
}



cg <- read.csv("cache/rare_common_h2_CG_k1-5.csv")
pdf("graphs/barplot_CG_revise2.pdf", width = 8, height=8)
mybarplot(df=cg)
dev.off()  

chg <- read.csv("cache/rare_common_h2_CHG_k1-5.csv")
pdf("graphs/barplot_CHG_revise2.pdf", width = 8, height=8)
mybarplot(df=chg)
dev.off()  


```







