---
title: "Figure 5"
output: NULL
author: Jinliang Yang
date: 10-01-2019
---


```{r setup, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE) 
knitr::opts_knit$set(root.dir=normalizePath('../')) 
#library(tidyverse)
```


# Main Figure 5

```{r}
source("lib/mplots.R")
source("lib/mcmcbc.R")

ob <- load("cache/interpop_CpG.RData")
cg1 <- sfsplot(res,burnin=0.2,rates=c(1E8,1E8,1E8), sfsplot="plotmean", Ne=150000, k=0:102, plot=FALSE)
cg2 <- mplot(res, burnin=0.2, rates=c(1E8,1E8,1E8), plot=FALSE)
# posterior mu [ 1.30559512528457e-06 ], nu [ 5.58672378104241e-08 ] and s [ 1.41280309789766e-05 ]

ob <- load("cache/interpop_CHG.RData")
chg1 <- sfsplot(res,burnin=0.2,rates=c(1E8,1E8,1E8), sfsplot="plotmean", Ne=150000, k=0:102, plot=FALSE)
chg2 <- mplot(res, burnin=0.2, rates=c(1E8,1E8,1E8), plot=FALSE)
# posterior mu [ 2.93528994835948e-06 ], nu [ 1.00452008499057e-07 ] and s [ 1.57231160388082e-05 ]

ob <- load("cache/interpop_CHH.RData")
chh1 <- sfsplot(res,burnin=0.2,rates=c(1E8,1E8,1E8), sfsplot="plotmean", Ne=150000, k=0:102, plot=FALSE)
chh2 <- mplot(res, burnin=0.2, rates=c(1E8,1E8,1E8), plot=FALSE)
# posterior mu [ 4.35832012973341e-05 ], nu [ 1.32690522162011e-07 ] and s [ 8.23674955927584e-10 ]

### SFS and transposons
### cowplot: combined
#library(grid)
# values=c("#8b7d6b", "#3b5998")
cg1 <- cg1 + 
  theme(legend.position = c(0.05, 0.9), legend.title=element_blank(), plot.title = element_text(size=20)) + 
  scale_fill_manual(values=c("#d9534f", "#428bca")) + 
  scale_size_manual(values=c(5, 3)) + ggtitle("CG") + ylab("")

chg1 <- chg1 + theme(plot.title = element_text(size=20)) + 
  scale_fill_manual(values=c("#d9534f", "#428bca"))  + 
  scale_size_manual(values=c(5, 3))  + ggtitle("CHG")

chh1 <- chh1 +
  theme(plot.title = element_text(size=20)) + 
  scale_fill_manual(values=c("#d9534f", "#428bca")) + 
  scale_size_manual(values=c(5, 3))  + 
  ggtitle("CHH") + ylab("") + labs(x="Number of methylated alleles") 

p1 <- plot_grid(cg1, chg1, ncol=1, rel_heights = c(1, 1), align="v")
p1
```

```{r}
pdf("graphs/Figure_sfs_interpop_CG_CHG.pdf", width=9, height=9)
ggdraw(p) + draw_plot_label(c("A", "B"), c(0, 0), c(1, 1/2), size=20)
dev.off()
```

```{r}
library("tidyr")
df1 <- read.csv("cache/table_msfs_par_interpop.csv")
df1$pop <- "crosspop"
df2 <- read.csv("cache/table_msfs_par_3pops.csv")
df2

df0 <- rbind(df1, df2)
df0$mu <- -log10(df0$mu)
df0$nu <- -log10(df0$nu)
df0$s <- df0$s * 150000 +0.1


df <- gather(data=df0, key=k, value="p", 1:3)
df <- subset(df, type != "CHH") 
p2 <- ggplot(df, aes(x=k, y=p, fill=pop)) +
    geom_bar(stat="identity", position=position_dodge()) +
    facet_grid(. ~ type) +
    theme_bw() +
    xlab("") +
    ylab("") +
    # https://www.color-hex.com/color-palette/73961
    #scale_fill_manual(values=c("#cc4141", "#72114b", "#e1cd07", "#5f9057", "#114c63", "#d3d3d3"),
    #                  name=c(""),
    #                  labels=c("Gene", "Down 5k", "Up 5k", "Intergenic", "TE", "Rest")) +
    scale_fill_manual(values=c("#ae5a41", "#1b85b8", "#559e83", "#c3cb71"),
                        name="", labels=c("Cross-Popls", "Landrace", "Maize", "Teosinte")) +
    scale_x_discrete(labels=c("-log10(mu)","-log10(nu)","Ne*s")) +
    theme(legend.position="top", axis.text=element_text(size=12), axis.title=element_text(size=15) )
  #########
p2


```


```{r}
pdf("graphs/Fig_pars.pdf", width=12, height=5)
ggdraw(p) + draw_plot_label(c("E"), x=0, y=1, size=20)
dev.off()

pleft <- plot_grid(cg1, chg1, p2, ncol=1, rel_heights = c(1, 1, 1.5), align="v")
pleft

pright <- cg2

pfinal <- plot_grid(pleft, pright, ncol=2, rel_widths = c(1,1.5))
pfinal
```


# Final Figure 5

```{r}

pdf("graphs/Figure_msfs.pdf", width=22, height=10)
ggdraw(pfinal) + draw_plot_label(c("A", "B", "C", "D"), c(0, 0, 0, 1/2.5), c(1, 2.5/3.5, 1.5/3.5, 1), size=20)
dev.off()
```


## Supplementary Figures

```{r}
pdf("graphs/Fig_mcmc_cg.pdf", width=16, height=9)
ggdraw(cg2) # + draw_plot_label(c("D"), x=0, y=1, size=20)
dev.off()

pdf("graphs/Fig_mcmc_chg.pdf", width=16, height=9)
ggdraw(chg2) # + draw_plot_label(c("E"), x=0, y=1, size=20)
dev.off()

```

