---
title: "Circos plot"
output: html_notebook
author: Jinliang Yang
date: 05-23-2019
---


```{r setup, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE) 
knitr::opts_knit$set(root.dir=normalizePath('../')) 
#library(tidyverse)
```


# Exploring circos plot


## Circos plot:

```{r}
#install.packages('BioCircos')
library(BioCircos)
# https://cran.r-project.org/web/packages/BioCircos/vignettes/BioCircos.html

## Create maize genome
agpv4 = list("chr1" = 307041717,
        "chr2" = 244442276,
        "chr3" = 235667834,
        "chr4" = 246994605,
        "chr5" = 223902240,
        "chr6" = 174033170,
        "chr7" = 182381542,
        "chr8" = 181122637,
        "chr9" = 159769782,
        "chr10" = 150982314)

BioCircos(genome = agpv4, genomeFillColor = c("tomato2", "darkblue"))


hichip <- subset(hichip, Chr_1 %in% 1:10)

links_chromosomes_1 = paste0("chr", as.numeric(as.character(hichip$Chr_1))) # Chromosomes on which the links should start
links_chromosomes_2 = paste0("chr", as.numeric(as.character(hichip$Chr_2))) # Chromosomes on which the links should end

links_pos_1 = hichip$S1
links_pos_2 = hichip$S2
#links_labels = c("Link 1", "Link 2", "Link 3")

tracklist = BioCircosBackgroundTrack("myBackgroundTrack", minRadius = 0, maxRadius = 0.9,
  borderSize = 0, fillColors = "#EEFFEE")  

tracklist = tracklist + BioCircosLinkTrack('myLinkTrack', links_chromosomes_1, links_pos_1,
  links_pos_1 + 500, links_chromosomes_2, links_pos_2, links_pos_2 + 7500, width="0.001em",
  maxRadius = 0.9)

BioCircos(tracklist, genome = agpv4, genomeFillColor = "PuOr",
  chrPad = 0.02, displayGenomeBorder = FALSE, yChr =  FALSE,
  genomeTicksDisplay = FALSE,  genomeLabelTextSize = "8pt", genomeLabelDy = 0)
```

