---
title: "Tb1 ChIP data"
output: html_notebook
author: Jinliang Yang
date: 11-02-2018
---


```{r setup, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE) 
knitr::opts_knit$set(root.dir=normalizePath('../../')) 
#library(tidyverse)
```


# Covert v3-v4



```{r}
chip <- read.csv("data/TB1_ChIP_interval_v3.csv")

bed <- chip[, c("chr", "start", "end", "name")]
bed$start <- bed$start -1
write.table(bed, "data/tb1_chip_v3.bed", sep="\t", row.names=FALSE, col.names=FALSE, quote=FALSE)
```

On server:

```{r}
lr <- read.csv("data/landraces_ordering_04092018.csv")
lr$id <- toupper(gsub(" ", "", lr$Plant.ID))

files <- list.files(path="/common/jyanglab/shared/Gen_Xu/methylation_level/Landrace", pattern="CHG", full.names = FALSE)
df <- data.frame(f=files, id=0)
df$id <- gsub("CHG_|.meth.*|-", "", df$f)

df <- merge(df, lr, by="id")
write.table(df, "cache/location_methylome_lr.csv", sep=",", row.names=FALSE, quote=FALSE)
```


### Use Google API to find the location 


```{r}
### step two: google API

# install.packages("RJSONIO", repos="http://cran.rstudio.com/")
library("RJSONIO")
source("lib/modified_geocode.R")
source("lib/data_cleaning.R")

googleloc <- function(df, google_api_key="AIzaSyA8zz", outcache, outtxt){
    ### df: [data.frame: loc] with user id and user reported location
    ### google_api_key:  use your own google AGP key, https://console.developers.google.com/
    
    ### search location using google API
    df <- df[order(df$loc),]
    geocode_apply <- function(x){
        geocode(x, source = "google", output = "all", override_limit = TRUE,
                api_key=google_api_key)
    }
    
    gres <- list()
    for(i in 1:nrow(df)){
      gres[[as.character(df$id[i])]] <- geocode_apply(df$loc[i])
    }
    #geocode_results <- sapply(as.character(df$loc), geocode_apply, simplify = F)
    #message(sprintf("###>>> [googleloc]: find location for %s users", length(geocode_results)))
    
    ### Step Three: clearning results
    out <- loc_cleaning(gres)
    
    #out <- cbind(df, out)
    if(!is.null(outcache)){
        save("geocode_results", file=outcache)
    }
    if(!is.null(outcache)){
        write.table(out, outtxt, sep="\t", row.names=FALSE)
    }
    
    return(out)
}


### read in the data from step one
df <- read.csv("cache/location_methylome_lr.csv")
names(df)[6] <- "loc"

df$loc <- gsub("Mexico ", "", df$loc)
df$loc <- paste0(df$loc, ", Mexico")
### use your own google AGP key, find it here: https://console.developers.google.com/
### it only allows up to 2500 free search per day
res1 <- googleloc(df, google_api_key="AIzaSyDy2BmGRwI9OB-HBdmn9rAKhCLpzxEmSgI", 
                  outcache="largedata/api_res.RData", 
                  outtxt="cache/location_res.txt")

test <- merge(df, res1, by="id")

```


## and plot them

```{r}
out <- read.delim("cache/location_res.txt")

# install.packages("ggmap")
library("ggmap")
library("ggplot2")
# install.packages("png")
library("png")

# us <- c(left = -125, bottom = 25.75, right = -67, top = 49)
mx <- c(left = -125, bottom = 25.75, right = -67, top = 49)
map <- get_stamenmap(mx, zoom = 5, maptype = "toner-lite")


######################################################################################
library(ggmap)
##lowerleftlon, lowerleftlat, upperrightlon, upperrightlat
#  or left/bottom/right/top bounding box
# myloc <- c(-150, -50, 0, 80)

myloc <- c(-150, 0, -60, 30)
mymap <- get_map(location=myloc, source="google", crop=FALSE, color="bw")
ggmap(mymap) + 
    geom_point(aes(x = lng, y = lat), data = out,
               alpha = .9, color="#d2691e", size = 5) 

```


