---
title: "Methylation ratio of the landraces at tb1 DMR"
output: html_notebook
author: Jinliang Yang
date: 11-02-2018
---


```{r setup, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE) 
knitr::opts_knit$set(root.dir=normalizePath('../../')) 
#library(tidyverse)
```

Teosinte lines:
Palmar Chico

The DMR:
270512569
270513049

Tb1:
270553676
270554776



# Get the methylation ratio


# Find the landrace ID and their origins

```{r}
library(data.table)
getmr <- function(files){
  outdf <- data.frame()
  for(i in 1:length(files)){
    r <- fread(files[i], data.table=FALSE, header=T)
    sub <- subset(r, Chr == 1 & Pos > 270512569 & Pos < 270513049)
    sub$totcov <- sub$count_methy + sub$count_unmethy
    tem <- data.frame(f=files[i], mr = mean(sub$methy_per), cov=mean(sub$totcov))
    outdf <- rbind(outdf, tem)
  }
  return(outdf)
}

files <- list.files(path="/common/jyanglab/shared/Gen_Xu/methylation_level/Landrace", pattern="CHG", full.names = TRUE)
out <- getmr(files)

out$f <- gsub(".*\\/", "", out$f)
out$id <- gsub("CHG_|.meth.*|-", "", out$f)

write.table(out, "cache/meth_ratio_lrs.csv", sep=",", row.names=FALSE, quote=FALSE)
```



## Plot landrace with different methylation ratios

```{r}
# install.packages("ggmap")
library("ggmap")
library("ggplot2")
# install.packages("png")
library("png")
library("RColorBrewer")
library(scales)

## lr location
out <- read.delim("cache/location_res.txt")
## lr meth ratio
mr <- read.csv("cache/meth_ratio_lrs.csv")

out <- merge(out, mr, by="id")
out <- out[order(out$mr), ]
out$col <- round(rescale(out$mr, to=c(5,1) ), 0)
# us <- c(left = -125, bottom = 25.75, right = -67, top = 49)
mx <- c(left = -125, bottom = 25.75, right = -67, top = 49)
map <- get_stamenmap(mx, zoom = 5, maptype = "toner-lite")


######################################################################################
library(ggmap)
##lowerleftlon, lowerleftlat, upperrightlon, upperrightlat
#  or left/bottom/right/top bounding box
# myloc <- c(-150, -50, 0, 80)

# Palmar Chico:

## Latitude : 18 41' 00'' 
## Longitude : -100 21' 00'' 

cols <- brewer.pal(5,"RdBu")
myloc <- c(-120, 10, -80, 30)
mymap <- get_map(location=myloc, source="google", crop=FALSE, color="bw")
ggmap(mymap) + 
    geom_point(aes(x = lng, y = lat), data = out,
               alpha = .9, color=cols[out$col], size = 5) +
  geom_point(aes(x = -100.21, y = 18.41), color="red", size = 8, shape=17)
  

```


### Methylation ratio vs. Evelation


```{r}

out$level <- "Hypo"
out[out$mr > 0.1, ]$level <- "Hyper"
fsize=10

p1 <- ggplot(out, aes(x=level, y=elv_m,
                      fill=factor(level, levels=c("Hypo", "Hyper"), labels=c("Hypo", "Hyper")))) + 
  geom_violin(trim=FALSE) +
  xlab("") +
  #ylim(c(0,1)) +
  ylab("Elevation (m)") +
  ggtitle("") + theme_bw() +
  labs(fill="Methylation Level") +
  theme(axis.text = element_text(size=fsize),
          axis.title=element_text(size=fsize, face="bold"),
          legend.title = element_text(size=fsize, face="bold"),
          legend.text = element_text(size=fsize))

p1
```

