---
title: "Step5: run array job for NA imputation"
output: NULL
author: Jinliang Yang
date: 12-12-2018
---


```{r setup, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE) 
knitr::opts_knit$set(root.dir=normalizePath('../../')) 
#library(tidyverse)
```

## Step4 and Step5: 




### Landrace
```{r}
library("huskeR")
run_Rcode(inputdf=data.frame(file=1:3, out=10), outdir="slurm-script", cmdno = 1, 
           rcodes = "profiling/3.popgen/3.A.4_setup_ajob_land.R",
           arrayshid = "slurm-script/run_land_array.sh",
           email="yangjl0930@gmail.com", 
            runinfo = c(TRUE, "jclarke", 10, "30G", "24:00:00"))
#
```



### Teosinte
```{r}
library("huskeR")
run_Rcode(inputdf=data.frame(file=1:3, out=10), outdir="slurm-script", cmdno = 1, 
           rcodes = "profiling/3.popgen/3.A.4_setup_ajob_teo.R",
           arrayshid = "slurm-script/run_rcode_array.sh",
           email="yangjl0930@gmail.com", 
            runinfo = c(TRUE, "jclarke", 10, "50G", "16:00:00"))
#
```



### Maize
```{r}
library("huskeR")
run_Rcode(inputdf=data.frame(file=1:3, out=10), outdir="slurm-script", cmdno = 1, 
           rcodes = "profiling/3.popgen/3.A.4_setup_ajob_maize.R",
           arrayshid = "slurm-script/run_maize_array.sh",
           email="yangjl0930@gmail.com", 
            runinfo = c(TRUE, "jclarke", 10, "50G", "36:00:00"))
#
```


## Missing Data filtering

Note that maize CG could not run successfully because of high missing rate:


```{r, eval=FALSE}

tb <- apply(mx[,-1], 2, function(x) sum(is.na(x)))
tb/nrow(mx)

mx <- mx[, -14:-15]
mx$missing <- apply(mx[,-1], 1, function(x) sum(is.na(x)))
table(mx$missing)

mx2 <- subset(mx, missing < 9 ) #9/15=60%
fwrite(mx2[, -16], "largedata/mr_100bp/elite_rm_CpG_matrix.csv", sep=",", row.names=FALSE, quote=FALSE)


######### CHG
mx <- fread("largedata/mr_100bp/elite_CHG_matrix.csv", data.table=FALSE)
tb <- apply(mx[,-1], 2, function(x) sum(is.na(x)))
tb/nrow(mx)

mx <- mx[, -14:-15]
mx$missing <- apply(mx[,-1], 1, function(x) sum(is.na(x)))
table(mx$missing)

mx2 <- subset(mx, missing < 9 ) #9/15=60%
fwrite(mx2[, -16], "largedata/mr_100bp/elite_rm_CHG_matrix.csv", sep=",", row.names=FALSE, quote=FALSE)

######### CHH
mx <- fread("largedata/mr_100bp/elite_CHH_matrix.csv", data.table=FALSE)
tb <- apply(mx[,-1], 2, function(x) sum(is.na(x)))
tb/nrow(mx)

mx <- mx[, -14:-15]
mx$missing <- apply(mx[,-1], 1, function(x) sum(is.na(x)))
table(mx$missing)

mx2 <- subset(mx, missing < 9 ) #9/15=60%
fwrite(mx2[, -16], "largedata/mr_100bp/elite_rm_CHH_matrix.csv", sep=",", row.names=FALSE, quote=FALSE)

```






### Test
```{r}
library(data.table)
mx <- fread("largedata/mr_100bp/teosinte_CpG_matrix.csv", data.table=FALSE)
mx$chr <- as.numeric(as.character(gsub("_.*", "", mx$uid)))
mx$pos <- as.numeric(as.character(gsub(".*_", "", mx$uid)))

# 135969172
df <- subset(mx, chr == 8 & pos > 135968500 & pos < 135970000)
#out <- doimpute(mx, ncols=2:17, binsize=1000)
write.table(df, "cache/vgt1_CG_teosinte.csv", sep=",", row.names=FALSE, quote=FALSE)

mx <- fread("largedata/mr_100bp/teosinte_CHG_matrix.csv", data.table=FALSE)
mx$chr <- as.numeric(as.character(gsub("_.*", "", mx$uid)))
mx$pos <- as.numeric(as.character(gsub(".*_", "", mx$uid)))

# 135969172,135969381
df <- subset(mx, chr == 8 & pos > 135968500 & pos < 135970000)
#out <- doimpute(mx, ncols=2:17, binsize=1000)
write.table(df, "cache/vgt1_CHG_teosinte.csv", sep=",", row.names=FALSE, quote=FALSE)


mx1 <- fread("largedata/mr_100bp/landrace_CpG_matrix.csv", data.table=FALSE)
mx1$chr <- as.numeric(as.character(gsub("_.*", "", mx1$uid)))
mx1$pos <- as.numeric(as.character(gsub(".*_", "", mx1$uid)))
# 135969172
df <- subset(mx1, chr == 8 & pos > 135968500 & pos < 135970000)
#out <- doimpute(mx, ncols=2:17, binsize=1000)
write.table(df, "cache/vgt1_CG_landrace.csv", sep=",", row.names=FALSE, quote=FALSE)

mx1 <- fread("largedata/mr_100bp/landrace_CHG_matrix.csv", data.table=FALSE)
mx1$chr <- as.numeric(as.character(gsub("_.*", "", mx1$uid)))
mx1$pos <- as.numeric(as.character(gsub(".*_", "", mx1$uid)))
# 135969172
df <- subset(mx1, chr == 8 & pos > 135968500 & pos < 135970000)
#out <- doimpute(mx, ncols=2:17, binsize=1000)
write.table(df, "cache/vgt1_CHG_landrace.csv", sep=",", row.names=FALSE, quote=FALSE)




# 135969172
df <- subset(mx, chr == 8 & pos > 135968500 & pos < 135970000)
write.table(df, "cache/vgt1_CHG.csv", sep=",", row.names=FALSE, quote=FALSE)

mx <- fread("largedata/mr_100bp/maize_CpG_matrix.csv", data.table=FALSE)
mx$chr <- as.numeric(as.character(gsub("_.*", "", mx$uid)))
mx$pos <- as.numeric(as.character(gsub(".*_", "", mx$uid)))

# 135969172
df <- subset(mx, chr == 8 & pos > 135968500 & pos < 135970000)
#out <- doimpute(mx, ncols=2:17, binsize=1000)
write.table(df, "cache/vgt1_CG.csv", sep=",", row.names=FALSE, quote=FALSE)

mx <- fread("largedata/mr_100bp/maize_CHG_matrix.csv", data.table=FALSE)
mx$chr <- as.numeric(as.character(gsub("_.*", "", mx$uid)))
mx$pos <- as.numeric(as.character(gsub(".*_", "", mx$uid)))

# 135969172
df <- subset(mx, chr == 8 & pos > 135968500 & pos < 135970000)
write.table(df, "cache/vgt1_CHG.csv", sep=",", row.names=FALSE, quote=FALSE)


df <- fread("/common/jyanglab/shared/Gen_Xu/07-08-2019-mr_basepair/Maize/CG/CpG_B73.meth_lev.txt")
d1 <- subset(df, Chr == 8 & Pos > 135968500 & Pos < 135970000)

df3 <- fread("/common/jyanglab/shared/Gen_Xu/07-08-2019-mr_basepair/Maize/CG/CpG_B37.meth_lev.txt")
d3 <- subset(df3, Chr == 8 & Pos > 135968500 & Pos < 135970000)

df2 <- fread("/common/jyanglab/shared/Gen_Xu/07-08-2019-mr_basepair/Maize/CG/CpG_Mo17.meth_lev.txt")
d2 <- subset(df2, Chr == 8 & Pos > 135968500 & Pos < 135970000)

df2 <- fread("/common/jyanglab/shared/Gen_Xu/07-08-2019-mr_basepair/Teosinte/CG/CpG_JRIAL2A.meth_lev.txt")
d2 <- subset(df2, Chr == 8 & Pos > 135968500 & Pos < 135970000)
```




