---
title: "Run MCMC BC"
output: NULL
author: Jinliang Yang
date: 01-30-2019
---


```{r setup, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE) 
knitr::opts_knit$set(root.dir=normalizePath('../../')) 
#library(tidyverse)
```




### Teosinte:

- 1000,000 runs
```{r, eval=FALSE}
library(devtools)
withr::with_libpaths(new = "/home/jyanglab/jyang21/bin/Rlib", install_github('yangjl/huskeR'))
# .libPaths()

library("huskeR")
run_Rcode(inputdf=data.frame(file=1:3, out=1), outdir="slurm-script", cmdno=1,
           rcodes = "profiling/3.popgen/3.B.2_setup_MCMC_teo.R",
           arrayshid = "slurm-script/run_MCMC_teo_array.sh",
           email="yangjl0930@gmail.com", runinfo = c(TRUE, "jyanglab", 2, "10G", "36:00:00"))


```

### Landrace:
```{r, eval=FALSE}
library(huskeR)
run_Rcode(inputdf=data.frame(file=1:3, out=1), outdir="slurm-script", cmdno=1,
           rcodes = "profiling/3.popgen/3.B.2_setup_MCMC_land.R",
           #arrayshid = "slurm-script/run_MCMC_land_array.sh",
           base_shid ="run_MCMC_land",
           email="yangjl0930@gmail.com", runinfo = c(TRUE, "jyanglab", 2, "10G", "36:00:00"))

#
```

### Maize:
```{r, eval=FALSE}
library("huskeR")
run_Rcode(inputdf=data.frame(file=1:3, out=1), outdir="slurm-script", cmdno=1,
           rcodes = "profiling/3.popgen/3.B.2_setup_MCMC_maize.R",
           base_shid ="run_MCMC_maize",
           email="yangjl0930@gmail.com", runinfo = c(TRUE, "jyanglab", 2, "10G", "36:00:00"))

#
```

------------------

```{r}
a <- load("largedata/sfs_teosinte_CHG.RData")
```





