---
title: "Start to compute SFS for each population and across populations"
output: NULL
author: Jinliang Yang
date: 01-28-2019
---


```{r setup, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE) 
knitr::opts_knit$set(root.dir=normalizePath('../../')) 
#library(tidyverse)
```


### get_SFS function

```{r, eval=FALSE}
library("data.table")

get_inter_sfs <- function(pop1="largedata/mr_100bp/teosinte_CpG_matrix_imp.csv", 
                   pop2="largedata/mr_100bp/landrace_CpG_matrix_imp.csv",
                   pop3="largedata/mr_100bp/maize_CpG_matrix_imp.csv",
                   outfile="cache/interpop_CpG.csv"){
    
    df1 <- fread(pop1, data.table=FALSE)
    df2 <- fread(pop2, data.table=FALSE)
    df3 <- fread(pop3, data.table=FALSE)
    #.SD is a data.table and holds all the values of all columns, except the one specified in by.
    #df <- as.data.table(df)
    #res <- cg[, lapply(.SD, mymean), by=bin, .SDcols = paste0("V",3:22)]
    #df <- merge(df1, df2[, -2:-3], by="uid")
    #df <- merge(df, df3[, -2:-3], by="uid")
    
    
    #idx <- which(names(df)[-1:-3] %in% "CpG_A632")
    #df <- as.data.frame(df)
    df1$f <- apply(df1[, -1:-3], 1, het_getcount)
    df2$f <- apply(df2[, -1:-3], 1, het_getcount)
    df3$f <- apply(df3[, -1:-3], 1, homo_getcount)
    
    df <- merge(df1[, c("uid", "f")], df2[, c("uid", "f")], by="uid")
    df <- merge(df, df3[, c("uid", "f")], by="uid")
    
    f1 <- table(df$f.x)
    write.table(f1, paste0(outfile, "_teo.csv"), sep=",", row.names=FALSE, quote=FALSE)
    
    f2 <- table(df$f.y)
    write.table(f2, paste0(outfile, "_land.csv"), sep=",", row.names=FALSE, quote=FALSE)
    
    f3 <- table(df$f)
    write.table(f3, paste0(outfile, "_mz.csv"), sep=",", row.names=FALSE, quote=FALSE)
    
    f <- df$f.x + df$f.y + df$f
    sfs <- table(f)
    write.table(sfs, paste0(outfile, "_pops.csv"), sep=",", row.names=FALSE, quote=FALSE)
}

het_getcount <- function(x, mmin=0.3, mmax=0.7){
    n0 <- sum(x < mmin) #0
    n2 <- sum(x > mmax) #2
    n1 <- sum(x >= mmin & x <= mmax) #1
    # n00 <- sum[x[38:51] < 0.5]
    # n11 <- sum[x[38:51] > 0.5]
    return(2*n2+n1)
}

homo_getcount <- function(x){
    #n00 <- sum[x < 0.5]
    n11 <- sum(x > 0.5)
    return(n11)
}
```

## inter-population SFS

```{r, eval=FALSE}
get_inter_sfs(pop1="largedata/mr_100bp/teosinte_CpG_matrix_imp.csv", 
              pop2="largedata/mr_100bp/landrace_CpG_matrix_imp.csv",
              pop3="largedata/mr_100bp/maize_CpG_matrix_imp.csv",
              outfile="cache/mcmc_res/new_msfs_CG")

get_inter_sfs(pop1="largedata/mr_100bp/teosinte_CHG_matrix_imp.csv", 
              pop2="largedata/mr_100bp/landrace_CHG_matrix_imp.csv",
              pop3="largedata/mr_100bp/maize_CHG_matrix_imp.csv",
              outfile="cache/mcmc_res/new_msfs_CHG")


```


-----------------

### CHH need to be modified:
```{r}
chh <- read.csv("cache/interpop_CHH.csv")
cg <- read.csv("cache/interpop_CpG.csv")
chg <- read.csv("cache/interpop_CHG.csv")

chh <- merge(cg, chh, by="f", all.x=T)
chh[is.na(chh[, 3]), 3] <- 0
chh <- chh[, c(1,3)]
names(chh) <- c("f", "Freq")
write.table(chh, "cache/interpop_CHH.csv", sep=",", row.names=FALSE, quote=FALSE)

t <- read.table("cache/interpop_CpG.csv")
```

## Plot supplementary figure for CHH

```{r}
library(ggplot2)

chh <- read.csv("cache/interpop_CHH.csv")
fsize=18
p <- ggplot(chh, aes(x=f, y=Freq, fill="blue")) +
          #geom_point() +
          geom_bar(stat = "identity", position = "dodge") +
          #scale_size_manual(values=c(2.5, 1.5)) +
          labs(y="Frequency", x="Number of Haplotypes", title="CHH") + 
          theme(legend.position="none") +
          #scale_y_log10() +
          theme(#axis.text=element_text(size=fsize),
                axis.title=element_text(size=fsize, face="bold"),
                legend.title = element_text(size=fsize, face="bold"),
                legend.text = element_text(size=fsize))

pdf("graphs/sfig_CHH_msfs.pdf", width=10, height=5)
p
dev.off()
```

