---
title: "Plot S figure for each pop"
output: NULL
author: Jinliang Yang
date: 02-26-2020
---


```{r setup, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE) 
knitr::opts_knit$set(root.dir=normalizePath('../../')) 
#library(tidyverse)
```


# Plot confidence interval:

```{r}

get_numus <- function(obfile="cache/mcmc_res/new_msfs_CG_pops.RData", burnin=0.2, Ne=150000){
    
    ob <- load(obfile)
    
    s.samples <- res[['samples']]$s
    nu.samples <- res[['samples']]$nu
    mu.samples <- res[['samples']]$mu
    l.samples <- res[['samples']]$l
    mu.acc <- res[['acc']]$mu
    nu.acc <- res[['acc']]$nu
    s.acc <- res[['acc']]$s
    
    s.samples=s.samples[(length(s.samples)*burnin+1):length(s.samples)]
    nu.samples=nu.samples[(length(nu.samples)*burnin+1):length(nu.samples)]
    mu.samples=mu.samples[(length(mu.samples)*burnin+1):length(mu.samples)]
    
    tem1 <- data.frame(mn=mean(Ne*s.samples), sd=sd(Ne*s.samples), med=median(Ne*s.samples), type="s")
    tem2 <- data.frame(mn=mean(-log10(nu.samples)), sd=sd(-log10(nu.samples)), med=median(-log10(nu.samples)), type="nu")
    tem3 <- data.frame(mn=mean(-log10(mu.samples)), sd=sd(-log10(mu.samples)), med=median(-log10(mu.samples)), type="mu")
    
    out <- rbind(tem1, tem2, tem3)
    return(out)
}


df11 <- get_numus(obfile="cache/mcmc_res/new_msfs_CG_land.RData", burnin=0.2, Ne=150000)
df11$pop <- "LR"

df12 <- get_numus(obfile="cache/mcmc_res/new_msfs_CG_mz.RData", burnin=0.2, Ne=150000)
df12$pop <- "MZ"

df13 <- get_numus(obfile="cache/mcmc_res/new_msfs_CG_teo.RData", burnin=0.2, Ne=150000)
df13$pop <- "TEO"

df1 <- rbind(df11, df12, df13)
df1$context <- "CG"

df21 <- get_numus(obfile="cache/mcmc_res/new_msfs_CHG_land.RData", burnin=0.2, Ne=150000)
df21$pop <- "LR"

df22 <- get_numus(obfile="cache/mcmc_res/new_msfs_CHG_mz.RData", burnin=0.2, Ne=150000)
df22$pop <- "MZ"

df23 <- get_numus(obfile="cache/mcmc_res/new_msfs_CHG_teo.RData", burnin=0.2, Ne=150000)
df23$pop <- "TEO"

df2 <- rbind(df21, df22, df23)
df2$context <- "CHG"

df <- rbind(df1, df2)   
```

```{r}
fsize=18
df$type <- factor(df$type, levels = c("mu", "nu", "s"))
df$pop <- factor(df$pop, levels = c("TEO", "LR", "MZ"))
pn <- ggplot(df, aes(x=type, y=mn, fill=pop)) +
    geom_bar(stat="identity", position=position_dodge()) +
    facet_grid(.~ context) +
    xlab("Posterior Estimates") +
    ylab("Value") +
    geom_errorbar(aes(ymin=mn-sd*100, ymax=mn+sd*100), width=.2,
                 position=position_dodge(.9)) +
    # https://www.color-hex.com/color-palette/73961
    #scale_fill_manual(values=c("#cc4141", "#72114b", "#e1cd07", "#5f9057", "#114c63", "#d3d3d3"),
    #                  name=c(""),
    #                  labels=c("Gene", "Down 5k", "Up 5k", "Intergenic", "TE", "Rest")) +
    scale_fill_manual(values=c("#E69F00","#56B4E9", "#009E73")) +
    scale_x_discrete(labels=c("-log10(mu)","-log10(nu)","Ne*s")) +
    theme(legend.position = "top", legend.title = element_blank(), axis.text=element_text(size=10),
          axis.title=element_text(size=fsize, face="bold"),
                legend.text = element_text(size=fsize))
  #########

pn

```

# Put figures together
```{r}

library(cowplot)
pdf("graphs/sfig_cg_chg_three.pdf", width=12, height=6)
ggdraw(pn)
dev.off()

```

### parameters:


```{r}
pdf("graphs/Figure_sfs_interpop.pdf", width=9, height=6)
ggdraw(p) + draw_plot_label(c("A", "B"), c(0, 0), c(1, 1/2), size=20)
dev.off()

pdf("graphs/Fig_mcmc_cg.pdf", width=12, height=9)
ggdraw(cg2) + draw_plot_label(c("D"), x=0, y=1, size=20)
dev.off()

pdf("graphs/Fig_mcmc_chg.pdf", width=12, height=9)
ggdraw(chg2) + draw_plot_label(c("E"), x=0, y=1, size=20)
dev.off()

pdf("graphs/Fig_mcmc_chh.pdf", width=12, height=9)
ggdraw(chh2) + draw_plot_label(c("F"), x=0, y=1, size=20)
dev.off()

plot_grid(cg1, ncol=1, align="v")


```


```{r}
library("tidyr")
df1 <- read.csv("cache/table_msfs_par_interpop.csv")
df1$pop <- "crosspop"
df2 <- read.csv("cache/table_msfs_par_3pops.csv")
df2

df0 <- rbind(df1, df2)
df0$mu <- -log10(df0$mu)
df0$nu <- -log10(df0$nu)
df0$s <- df0$s * 150000 +0.1


df <- gather(data=df0, key=k, value="p", 1:3)
  
p <- ggplot(df, aes(x=k, y=p, fill=pop)) +
    geom_bar(stat="identity", position=position_dodge()) +
    facet_grid(. ~ type) +
    theme_bw() +
    xlab("") +
    ylab("") +
    # https://www.color-hex.com/color-palette/73961
    #scale_fill_manual(values=c("#cc4141", "#72114b", "#e1cd07", "#5f9057", "#114c63", "#d3d3d3"),
    #                  name=c(""),
    #                  labels=c("Gene", "Down 5k", "Up 5k", "Intergenic", "TE", "Rest")) +
    scale_fill_manual(values=c("#ae5a41", "#1b85b8", "#559e83", "#c3cb71"),
                        name="", labels=c("Cross-Popls", "Landrace", "Maize", "Teosinte")) +
    scale_x_discrete(labels=c("-log10(mu)","-log10(nu)","Ne*s")) +
    theme(legend.position="top", axis.text=element_text(size=12), axis.title=element_text(size=15) )
  #########
p

pdf("graphs/Fig_pars.pdf", width=12, height=5)
ggdraw(p) + draw_plot_label(c("E"), x=0, y=1, size=20)
dev.off()

```


