---
title: "Run MCMC BC"
output: html_notebook
author: Jinliang Yang
date: 01-30-2019
---


```{r setup, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE) 
knitr::opts_knit$set(root.dir=normalizePath('../../')) 
#library(tidyverse)
```


### Teosinte Genome-wide results

```{r}
### Jinliang Yang
### 10-14-2016
### run MCMC for comet on chr10

source("lib/mplots.R")
source("lib/mcmcbc.R")

ob <- load("cache/interpop_CpG.RData")
sfsplot(res,burnin=0.2,rates=c(1E8,1E8,1E8), sfsplot="plotmean", Ne=150000, k=0:102)
out1 <- mplot(res, burnin=0.2, rates=c(1E8,1E8,1E8))
# posterior mu [ 1.30559512528457e-06 ], nu [ 5.58672378104241e-08 ] and s [ 1.41280309789766e-05 ]

ob <- load("cache/interpop_CHG.RData")
sfsplot(res,burnin=0.2,rates=c(1E8,1E8,1E8), sfsplot="plotmean", Ne=150000, k=0:102)
out2 <- mplot(res, burnin=0.2, rates=c(1E8,1E8,1E8))
# posterior mu [ 2.93528994835948e-06 ], nu [ 1.00452008499057e-07 ] and s [ 1.57231160388082e-05 ]


ob <- load("cache/interpop_CHH.RData")
sfsplot(res,burnin=0.2,rates=c(1E8,1E8,1E8), sfsplot="plotmean", Ne=150000, k=0:102)
out3 <- mplot(res, burnin=0.2, rates=c(1E8,1E8,1E8))
# posterior mu [ 4.35832012973341e-05 ], nu [ 1.32690522162011e-07 ] and s [ 8.23674955927584e-10 ]


```


### parameters:

```{r}
df <- rbind(out1, out2, out3)
df <- as.data.frame(df)
names(df) <- c("mu", "nu", "s")
df$type <- c("CG", "CHG", "CHH")
write.table(df, "cache/table_msfs_par_interpop.csv", sep=",", row.names=FALSE, quote=FALSE)
```



```{r}
source("lib/mcmcbc.R")
ob <- load("cache/interpop_CpG.RData")

post.nu <- res$samples$nu[10000]
post.mu <- res$samples$mu[10000]
post.s <- res$samples$s[10000]
k=0:102
n=max(k)
Ne=100000
my_sfs <- res$my_sfs
  
post_sfs=sapply(k,function(K){
     log(choose(n,K))+(f1(mean(post.nu)*4*Ne+K,mean(post.mu)*4*Ne+mean(post.nu)*4*Ne+n,mean(post.s)*4*Ne)+proch(mean(post.nu)*4*Ne,K)+proch(mean(post.mu)*4*Ne,n-K))-(f1(mean(post.nu)*4*Ne,mean(post.mu)*4*Ne+mean(post.nu)*4*Ne,mean(post.s)*4*Ne)+proch(mean(post.mu)*4*Ne+mean(post.nu)*4*Ne,n))})
post_sfs=post_sfs-max(post_sfs)
    post_sfs=exp(post_sfs)/sum(exp(post_sfs))*sum(my_sfs)

```


