---
title: "Plot par figures"
output: NULL
author: Jinliang Yang
date: 02-26-2019
---


```{r setup, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE) 
knitr::opts_knit$set(root.dir=normalizePath('../../')) 
#library(tidyverse)
```

### Figure 1: Inter-population SFS

```{r}
source("lib/mplots.R")
source("lib/mcmcbc.R")

ob <- load("cache/mcmc_res/new_msfs_CG_pops.RData")
cg1 <- sfsplot(res,burnin=0.2,rates=c(1E8,1E8,1E8), sfsplot="plotmean", Ne=150000, k=0:88, plot=FALSE)
cg2 <- mplot(res, burnin=0.2, rates=c(1E8,1E8,1E8), plot=FALSE)
# posterior mu [ 1.30559512528457e-06 ], nu [ 5.58672378104241e-08 ] and s [ 1.41280309789766e-05 ]

ob <- load("cache/mcmc_res/new_msfs_CHG_pops.RData")
chg1 <- sfsplot(res,burnin=0.2,rates=c(1E8,1E8,1E8), sfsplot="plotmean", Ne=150000, k=0:88, plot=FALSE)
chg2 <- mplot(res, burnin=0.2, rates=c(1E8,1E8,1E8), plot=FALSE)
# posterior mu [ 2.93528994835948e-06 ], nu [ 1.00452008499057e-07 ] and s [ 1.57231160388082e-05 ]


### SFS and transposons
### cowplot: combined
#library(grid)
# values=c("#8b7d6b", "#3b5998")
cg1 <- cg1 + 
  scale_fill_manual(values=c("#999999", "#E69F00")) + 
  scale_size_manual(values=c(5, 3)) + ggtitle("CG") +
  theme(legend.position = c(0.05, 0.9), legend.title=element_blank(), plot.title = element_text(size=18)) 

chg1 <- chg1 + 
  scale_fill_manual(values=c("#999999", "#56B4E9"))  + 
  scale_size_manual(values=c(5, 3))  + ggtitle("CHG") +
  xlab("Number of Haplotypes") +
  theme(legend.position = c(0.05, 0.9), legend.title=element_blank(), plot.title = element_text(size=18)) 

p <- plot_grid(cg1, chg1, ncol=1, rel_heights = c(1, 1), align="v")
p


```

# Plot confidence interval:

```{r}

get_numus <- function(obfile="cache/mcmc_res/new_msfs_CG_pops.RData", burnin=0.2, Ne=150000){
    
    ob <- load(obfile)
    
    s.samples <- res[['samples']]$s
    nu.samples <- res[['samples']]$nu
    mu.samples <- res[['samples']]$mu
    l.samples <- res[['samples']]$l
    mu.acc <- res[['acc']]$mu
    nu.acc <- res[['acc']]$nu
    s.acc <- res[['acc']]$s
    
    s.samples=s.samples[(length(s.samples)*burnin+1):length(s.samples)]
    nu.samples=nu.samples[(length(nu.samples)*burnin+1):length(nu.samples)]
    mu.samples=mu.samples[(length(mu.samples)*burnin+1):length(mu.samples)]
    
    tem1 <- data.frame(mn=mean(Ne*s.samples), sd=sd(Ne*s.samples), med=median(Ne*s.samples), type="s")
    tem2 <- data.frame(mn=mean(-log10(nu.samples)), sd=sd(-log10(nu.samples)), med=median(-log10(nu.samples)), type="nu")
    tem3 <- data.frame(mn=mean(-log10(mu.samples)), sd=sd(-log10(mu.samples)), med=median(-log10(mu.samples)), type="mu")
    
    out <- rbind(tem1, tem2, tem3)
    return(out)
}


### files
files <- list.files("largedata/revise_fig1", pattern="RData", full.names = T)

out <- data.frame()
for(i in 1:length(files)){
  ne <- gsub("_ft.*", "", files[i])
  ne <- as.numeric(as.character(gsub(".*_", "", ne)))
  df11 <- get_numus(obfile=files[i], burnin=0.2, Ne=ne)
  df11$par <- files[i]
  df11$ne <- ne
  out <- rbind(out, df11)
}

#out$class <- gsub(".*\\/|_pop3.*", "", out$par)


out$context <- gsub("_pops.*|.*msfs_", "", out$par)
write.table(out, "cache/response_msfs_ne.csv", sep=",", row.names=FALSE, quote=FALSE)    
```

```{r}
library("tidyr")
library("ggplot2")
df <- read.csv("cache/response_msfs_ne.csv")

#df <- gather(data=df0, key=k, value="p", 1:3)


fsize=18
df$ne <- factor(df$ne, levels = c("50000", "1e+05", "5e+05", "1e+06"))



p1 <- ggplot(df, aes(x=type, y=mn, fill=ne)) +
    geom_bar(stat="identity", position=position_dodge()) +
    facet_grid( . ~ context) +
    xlab("Posterior Estimates") +
    ylab("Value") +
    geom_errorbar(aes(ymin=mn-sd, ymax=mn+sd), width=.2,
                 position=position_dodge(.9)) +
    # https://www.color-hex.com/color-palette/73961
    scale_fill_manual(values=c("#cc4141", "#72114b", "#e1cd07", "#5f9057"),
                      name=c("Ne"),
                      labels=c("5e+4", "1e+5", "5e+5", "1e+6")) +
    #scale_fill_manual(values=c("#cc4141", "#72114b", "#e1cd07", "#5f9057", "#114c63")) +
    #labs(fill = "Dose (mg)") +
    scale_x_discrete(labels=c("-log10(mu)","-log10(nu)", "Ne*s")) +
    theme(legend.position = "top", plot.title = element_text(size=20), axis.text=element_text(size=15),
          strip.text.x = element_text(size = 20, face = "bold"),
          axis.title=element_text(size=fsize, face="bold"),
                legend.title = element_text(size=fsize, face="bold"),
                legend.text = element_text(size=fsize))
  #########

p1

```

# Put figures together
```{r}


### SFS and transposons
### cowplot: combined
pout <- plot_grid(p, pn, ncol=2, rel_widths=c(2,1), align="h")
pout

pdf("graphs/Figure1_cg_chg.pdf", width=12, height=6)
ggdraw(pout) + draw_plot_label(c("A", "B", "C" ), c(0, 0, 2/3), c(1, 1/2, 1), size=20)
dev.off()

```

### parameters:


```{r}
pdf("graphs/Figure_sfs_interpop.pdf", width=9, height=6)
ggdraw(p) + draw_plot_label(c("A", "B"), c(0, 0), c(1, 1/2), size=20)
dev.off()

pdf("graphs/Fig_mcmc_cg.pdf", width=12, height=9)
ggdraw(cg2) + draw_plot_label(c("D"), x=0, y=1, size=20)
dev.off()

pdf("graphs/Fig_mcmc_chg.pdf", width=12, height=9)
ggdraw(chg2) + draw_plot_label(c("E"), x=0, y=1, size=20)
dev.off()

pdf("graphs/Fig_mcmc_chh.pdf", width=12, height=9)
ggdraw(chh2) + draw_plot_label(c("F"), x=0, y=1, size=20)
dev.off()

plot_grid(cg1, ncol=1, align="v")


```


```{r}
library("tidyr")
df1 <- read.csv("cache/table_msfs_par_interpop.csv")
df1$pop <- "crosspop"
df2 <- read.csv("cache/table_msfs_par_3pops.csv")
df2

df0 <- rbind(df1, df2)
df0$mu <- -log10(df0$mu)
df0$nu <- -log10(df0$nu)
df0$s <- df0$s * 150000 +0.1


df <- gather(data=df0, key=k, value="p", 1:3)
  
p <- ggplot(df, aes(x=k, y=p, fill=pop)) +
    geom_bar(stat="identity", position=position_dodge()) +
    facet_grid(. ~ type) +
    theme_bw() +
    xlab("") +
    ylab("") +
    # https://www.color-hex.com/color-palette/73961
    #scale_fill_manual(values=c("#cc4141", "#72114b", "#e1cd07", "#5f9057", "#114c63", "#d3d3d3"),
    #                  name=c(""),
    #                  labels=c("Gene", "Down 5k", "Up 5k", "Intergenic", "TE", "Rest")) +
    scale_fill_manual(values=c("#ae5a41", "#1b85b8", "#559e83", "#c3cb71"),
                        name="", labels=c("Cross-Popls", "Landrace", "Maize", "Teosinte")) +
    scale_x_discrete(labels=c("-log10(mu)","-log10(nu)","Ne*s")) +
    theme(legend.position="top", axis.text=element_text(size=12), axis.title=element_text(size=15) )
  #########
p

pdf("graphs/Fig_pars.pdf", width=12, height=5)
ggdraw(p) + draw_plot_label(c("E"), x=0, y=1, size=20)
dev.off()

```


