---
title: "get posteriors from MCMC BC"
output: NULL
author: Jinliang Yang
date: 07-03-2020
---


```{r setup, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE) 
knitr::opts_knit$set(root.dir=normalizePath('../../')) 
#library(tidyverse)
```


### Teosinte Genome-wide results

```{r}
### Jinliang Yang
### 10-14-2016
### run MCMC for comet on chr10

source("lib/mplots.R")
source("lib/mcmcbc.R")

get_numus <- function(obfile="cache/mcmc_res/new_msfs_CG_pops.RData", burnin=0.2, Ne=150000){
    
    ob <- load(obfile)
    
    s.samples <- res[['samples']]$s
    nu.samples <- res[['samples']]$nu
    mu.samples <- res[['samples']]$mu
    l.samples <- res[['samples']]$l
    mu.acc <- res[['acc']]$mu
    nu.acc <- res[['acc']]$nu
    s.acc <- res[['acc']]$s
    
    s.samples=s.samples[(length(s.samples)*burnin+1):length(s.samples)]
    nu.samples=nu.samples[(length(nu.samples)*burnin+1):length(nu.samples)]
    mu.samples=mu.samples[(length(mu.samples)*burnin+1):length(mu.samples)]
    
    tem1 <- data.frame(mn=mean(Ne*s.samples), sd=sd(Ne*s.samples), med=median(Ne*s.samples), type="s")
    tem2 <- data.frame(mn=mean(-log10(nu.samples)), sd=sd(-log10(nu.samples)), med=median(-log10(nu.samples)), type="nu")
    tem3 <- data.frame(mn=mean(-log10(mu.samples)), sd=sd(-log10(mu.samples)), med=median(-log10(mu.samples)), type="mu")
    
    out <- rbind(tem1, tem2, tem3)
    return(out)
}

### files
files <- list.files("cache/mcmc_revise", pattern="RData", full.names = T)

out <- data.frame()
for(i in 1:length(files)){
  df11 <- get_numus(obfile=files[i], burnin=0.2, Ne=150000)
  df11$par <- files[i]
  out <- rbind(out, df11)
}
out$rates <- gsub(".*pops_", "", out$par)
out$psd <- gsub(".*_", "", out$rates)
out$rates <- gsub("_.*", "", out$rates)
out$psd <- gsub(".RData", "", out$psd)

write.table(out, "cache/response_prior.csv", sep=",", row.names=FALSE, quote=FALSE)

```


### plot the results:


```{r}
library("tidyr")
library(ggplot2)
df0 <- read.csv("cache/response_prior.csv")
df0$context <- gsub(".*new_msfs_|_pops.*", "", df0$par)
#df <- gather(data=df0, key=k, value="p", 1:3)

df <- subset(df0, psd == 0.05)  
fsize=18
df$type <- factor(df$type, levels = c("mu", "nu", "s"))
df$rates <- factor(df$rates, levels = c("100", "10000", "1e+06", "1e+08", "1e+10"))

p1 <- ggplot(df, aes(x=type, y=mn, fill=rates)) +
    geom_bar(stat="identity", position=position_dodge()) +
    facet_grid( . ~ context) +
    xlab("Posterior Estimates") +
    ylab("Value") +
    geom_errorbar(aes(ymin=mn-sd, ymax=mn+sd), width=.2,
                 position=position_dodge(.9)) +
    # https://www.color-hex.com/color-palette/73961
    scale_fill_manual(values=c("#cc4141", "#72114b", "#e1cd07", "#5f9057", "#114c63"),
                      name=c("Prior lambda"),
                      labels=c("10^2", "10^4", "10^6", "10^8", "10^10")) +
    #scale_fill_manual(values=c("#cc4141", "#72114b", "#e1cd07", "#5f9057", "#114c63")) +
    #labs(fill = "Dose (mg)") +
    scale_x_discrete(labels=c("-log10(mu)","-log10(nu)", "Ne*s")) +
    theme(legend.position = c(0.9, 0.7), plot.title = element_text(size=20), axis.text=element_text(size=15),
          strip.text.x = element_text(size = 20, face = "bold"),
          axis.title=element_text(size=fsize, face="bold"),
                legend.title = element_text(size=fsize, face="bold"),
                legend.text = element_text(size=fsize))
  #########

p1

```

```{r}

df0 <- read.csv("cache/response_prior.csv")
df0$context <- gsub(".*new_msfs_|_pops.*", "", df0$par)
#df <- gather(data=df0, key=k, value="p", 1:3)

df <- subset(df0, rates == 1e+06)  
fsize=18
df$type <- factor(df$type, levels = c("mu", "nu", "s"))
df$psd <- factor(df$psd, levels = c("0.01", "0.05", "0.1"))

p2 <- ggplot(df, aes(x=type, y=mn, fill=psd)) +
    geom_bar(stat="identity", position=position_dodge()) +
    facet_grid( . ~ context) +
    xlab("Posterior Estimates") +
    ylab("Value") +
    geom_errorbar(aes(ymin=mn-sd, ymax=mn+sd), width=.2,
                 position=position_dodge(.9)) +
    # https://www.color-hex.com/color-palette/73961
    scale_fill_manual(values=c("#cc4141", "#72114b", "#e1cd07"),
                      name=c("Prior sd"),
                      labels=c("0.01", "0.05", "0.1")) +
    #scale_fill_manual(values=c("#cc4141", "#72114b", "#e1cd07", "#5f9057", "#114c63")) +
    #labs(fill = "Dose (mg)") +
    scale_x_discrete(labels=c("-log10(mu)","-log10(nu)", "Ne*s")) +
    theme(legend.position = c(0.9, 0.7), plot.title = element_text(size=20), axis.text=element_text(size=15),
          strip.text.x = element_text(size = 20, face = "bold"),
          axis.title=element_text(size=fsize, face="bold"),
                legend.title = element_text(size=fsize, face="bold"),
                legend.text = element_text(size=fsize))
  #########

p2

```


```{r}
library("cowplot")
pdf("graphs/SFig_prior_rates.pdf", width=12, height=10)
plot_grid(p1, p2, ncol=1, labels = "AUTO", label_size = 26)
dev.off()
```



